import my_work_history


def test_fetch_info() -> None:
    test_info = my_work_history.fetch_info_for_date(
        date="2026-01-05",
        username="codycbakerphd",
    )
    expected_info = {
        "type-issues_date-2026+01+05": {
            "total_count": 1,
            "incomplete_results": False,
            "items": [
                {
                    "url": "https://api.github.com/repos/con/nwb2bids/issues/252",
                    "repository_url": "https://api.github.com/repos/con/nwb2bids",
                    "labels_url": "https://api.github.com/repos/con/nwb2bids/issues/252/labels{/name}",
                    "comments_url": "https://api.github.com/repos/con/nwb2bids/issues/252/comments",
                    "events_url": "https://api.github.com/repos/con/nwb2bids/issues/252/events",
                    "html_url": "https://github.com/con/nwb2bids/issues/252",
                    "id": 3782320956,
                    "node_id": "I_kwDOLaBElc7hcaM8",
                    "number": 252,
                    "title": "Investigate: run time on 000008",
                    "user": {
                        "login": "CodyCBakerPhD",
                        "id": 51133164,
                        "node_id": "MDQ6VXNlcjUxMTMzMTY0",
                        "avatar_url": "https://avatars.githubusercontent.com/u/51133164?v=4",
                        "gravatar_id": "",
                        "url": "https://api.github.com/users/CodyCBakerPhD",
                        "html_url": "https://github.com/CodyCBakerPhD",
                        "followers_url": "https://api.github.com/users/CodyCBakerPhD/followers",
                        "following_url": "https://api.github.com/users/CodyCBakerPhD/following{/other_user}",
                        "gists_url": "https://api.github.com/users/CodyCBakerPhD/gists{/gist_id}",
                        "starred_url": "https://api.github.com/users/CodyCBakerPhD/starred{/owner}{/repo}",
                        "subscriptions_url": "https://api.github.com/users/CodyCBakerPhD/subscriptions",
                        "organizations_url": "https://api.github.com/users/CodyCBakerPhD/orgs",
                        "repos_url": "https://api.github.com/users/CodyCBakerPhD/repos",
                        "events_url": "https://api.github.com/users/CodyCBakerPhD/events{/privacy}",
                        "received_events_url": "https://api.github.com/users/CodyCBakerPhD/received_events",
                        "type": "User",
                        "user_view_type": "public",
                        "site_admin": False,
                    },
                    "labels": [
                        {
                            "id": 9462365404,
                            "node_id": "LA_kwDOLaBElc8AAAACNAA83A",
                            "url": "https://api.github.com/repos/con/nwb2bids/labels/performance",
                            "name": "performance",
                            "color": "f4b2d8",
                            "default": False,
                            "description": "Improve performance of an existing feature",
                        }
                    ],
                    "state": "open",
                    "locked": False,
                    "assignees": [],
                    "milestone": None,
                    "comments": 1,
                    "created_at": "2026-01-05T17:36:59Z",
                    "updated_at": "2026-01-26T15:26:58Z",
                    "closed_at": None,
                    "assignee": None,
                    "author_association": "COLLABORATOR",
                    "type": {
                        "id": 1706307,
                        "node_id": "IT_kwDOAMredc4AGglD",
                        "name": "Task",
                        "description": "A specific piece of work",
                        "color": "yellow",
                        "created_at": "2024-01-25T14:25:30Z",
                        "updated_at": "2024-07-26T10:29:52Z",
                        "is_enabled": True,
                    },
                    "active_lock_reason": None,
                    "sub_issues_summary": {"total": 0, "completed": 0, "percent_completed": 0},
                    "issue_dependencies_summary": {
                        "blocked_by": 0,
                        "total_blocked_by": 0,
                        "blocking": 0,
                        "total_blocking": 0,
                    },
                    "body": (
                        "@asmacdo noted that `nwb2bids` takes a long time to run on Dandiset 000008\n\n"
                        "Should investigate why"
                    ),
                    "reactions": {
                        "url": "https://api.github.com/repos/con/nwb2bids/issues/252/reactions",
                        "total_count": 0,
                        "+1": 0,
                        "-1": 0,
                        "laugh": 0,
                        "hooray": 0,
                        "confused": 0,
                        "heart": 0,
                        "rocket": 0,
                        "eyes": 0,
                    },
                    "timeline_url": "https://api.github.com/repos/con/nwb2bids/issues/252/timeline",
                    "performed_via_github_app": None,
                    "state_reason": None,
                    "pinned_comment": None,
                    "score": 1.0,
                }
            ],
        },
        "type-prs_date-2026+01+05": {
            "total_count": 3,
            "incomplete_results": False,
            "items": [
                {
                    "url": "https://api.github.com/repos/con/nwb2bids/issues/254",
                    "repository_url": "https://api.github.com/repos/con/nwb2bids",
                    "labels_url": "https://api.github.com/repos/con/nwb2bids/issues/254/labels{/name}",
                    "comments_url": "https://api.github.com/repos/con/nwb2bids/issues/254/comments",
                    "events_url": "https://api.github.com/repos/con/nwb2bids/issues/254/events",
                    "html_url": "https://github.com/con/nwb2bids/pull/254",
                    "id": 3783238772,
                    "node_id": "PR_kwDOLaBElc67n5j_",
                    "number": 254,
                    "title": "Added icephys support",
                    "user": {
                        "login": "CodyCBakerPhD",
                        "id": 51133164,
                        "node_id": "MDQ6VXNlcjUxMTMzMTY0",
                        "avatar_url": "https://avatars.githubusercontent.com/u/51133164?v=4",
                        "gravatar_id": "",
                        "url": "https://api.github.com/users/CodyCBakerPhD",
                        "html_url": "https://github.com/CodyCBakerPhD",
                        "followers_url": "https://api.github.com/users/CodyCBakerPhD/followers",
                        "following_url": "https://api.github.com/users/CodyCBakerPhD/following{/other_user}",
                        "gists_url": "https://api.github.com/users/CodyCBakerPhD/gists{/gist_id}",
                        "starred_url": "https://api.github.com/users/CodyCBakerPhD/starred{/owner}{/repo}",
                        "subscriptions_url": "https://api.github.com/users/CodyCBakerPhD/subscriptions",
                        "organizations_url": "https://api.github.com/users/CodyCBakerPhD/orgs",
                        "repos_url": "https://api.github.com/users/CodyCBakerPhD/repos",
                        "events_url": "https://api.github.com/users/CodyCBakerPhD/events{/privacy}",
                        "received_events_url": "https://api.github.com/users/CodyCBakerPhD/received_events",
                        "type": "User",
                        "user_view_type": "public",
                        "site_admin": False,
                    },
                    "labels": [
                        {
                            "id": 6631660905,
                            "node_id": "LA_kwDOLaBElc8AAAABi0cdaQ",
                            "url": "https://api.github.com/repos/con/nwb2bids/labels/enhancement",
                            "name": "enhancement",
                            "color": "a2eeef",
                            "default": True,
                            "description": "New feature or request",
                        },
                        {
                            "id": 9462364765,
                            "node_id": "LA_kwDOLaBElc8AAAACNAA6XQ",
                            "url": "https://api.github.com/repos/con/nwb2bids/labels/minor",
                            "name": "minor",
                            "color": "f1a60e",
                            "default": False,
                            "description": "Increment the minor version when merged",
                        },
                        {
                            "id": 9462365024,
                            "node_id": "LA_kwDOLaBElc8AAAACNAA7YA",
                            "url": "https://api.github.com/repos/con/nwb2bids/labels/release",
                            "name": "release",
                            "color": "007f70",
                            "default": False,
                            "description": "Create a release when this pr is merged",
                        },
                        {
                            "id": 9462365474,
                            "node_id": "LA_kwDOLaBElc8AAAACNAA9Ig",
                            "url": "https://api.github.com/repos/con/nwb2bids/labels/released",
                            "name": "released",
                            "color": "11a990",
                            "default": False,
                            "description": "This issue/pull request has been released.",
                        },
                    ],
                    "state": "closed",
                    "locked": False,
                    "assignees": [
                        {
                            "login": "CodyCBakerPhD",
                            "id": 51133164,
                            "node_id": "MDQ6VXNlcjUxMTMzMTY0",
                            "avatar_url": "https://avatars.githubusercontent.com/u/51133164?v=4",
                            "gravatar_id": "",
                            "url": "https://api.github.com/users/CodyCBakerPhD",
                            "html_url": "https://github.com/CodyCBakerPhD",
                            "followers_url": "https://api.github.com/users/CodyCBakerPhD/followers",
                            "following_url": "https://api.github.com/users/CodyCBakerPhD/following{/other_user}",
                            "gists_url": "https://api.github.com/users/CodyCBakerPhD/gists{/gist_id}",
                            "starred_url": "https://api.github.com/users/CodyCBakerPhD/starred{/owner}{/repo}",
                            "subscriptions_url": "https://api.github.com/users/CodyCBakerPhD/subscriptions",
                            "organizations_url": "https://api.github.com/users/CodyCBakerPhD/orgs",
                            "repos_url": "https://api.github.com/users/CodyCBakerPhD/repos",
                            "events_url": "https://api.github.com/users/CodyCBakerPhD/events{/privacy}",
                            "received_events_url": "https://api.github.com/users/CodyCBakerPhD/received_events",
                            "type": "User",
                            "user_view_type": "public",
                            "site_admin": False,
                        }
                    ],
                    "milestone": None,
                    "comments": 3,
                    "created_at": "2026-01-05T23:58:31Z",
                    "updated_at": "2026-01-07T19:31:18Z",
                    "closed_at": "2026-01-07T19:30:22Z",
                    "assignee": {
                        "login": "CodyCBakerPhD",
                        "id": 51133164,
                        "node_id": "MDQ6VXNlcjUxMTMzMTY0",
                        "avatar_url": "https://avatars.githubusercontent.com/u/51133164?v=4",
                        "gravatar_id": "",
                        "url": "https://api.github.com/users/CodyCBakerPhD",
                        "html_url": "https://github.com/CodyCBakerPhD",
                        "followers_url": "https://api.github.com/users/CodyCBakerPhD/followers",
                        "following_url": "https://api.github.com/users/CodyCBakerPhD/following{/other_user}",
                        "gists_url": "https://api.github.com/users/CodyCBakerPhD/gists{/gist_id}",
                        "starred_url": "https://api.github.com/users/CodyCBakerPhD/starred{/owner}{/repo}",
                        "subscriptions_url": "https://api.github.com/users/CodyCBakerPhD/subscriptions",
                        "organizations_url": "https://api.github.com/users/CodyCBakerPhD/orgs",
                        "repos_url": "https://api.github.com/users/CodyCBakerPhD/repos",
                        "events_url": "https://api.github.com/users/CodyCBakerPhD/events{/privacy}",
                        "received_events_url": "https://api.github.com/users/CodyCBakerPhD/received_events",
                        "type": "User",
                        "user_view_type": "public",
                        "site_admin": False,
                    },
                    "author_association": "COLLABORATOR",
                    "type": None,
                    "active_lock_reason": None,
                    "draft": False,
                    "pull_request": {
                        "url": "https://api.github.com/repos/con/nwb2bids/pulls/254",
                        "html_url": "https://github.com/con/nwb2bids/pull/254",
                        "diff_url": "https://github.com/con/nwb2bids/pull/254.diff",
                        "patch_url": "https://github.com/con/nwb2bids/pull/254.patch",
                        "merged_at": "2026-01-07T19:30:22Z",
                    },
                    "body": "WIP, check back later",
                    "reactions": {
                        "url": "https://api.github.com/repos/con/nwb2bids/issues/254/reactions",
                        "total_count": 0,
                        "+1": 0,
                        "-1": 0,
                        "laugh": 0,
                        "hooray": 0,
                        "confused": 0,
                        "heart": 0,
                        "rocket": 0,
                        "eyes": 0,
                    },
                    "timeline_url": "https://api.github.com/repos/con/nwb2bids/issues/254/timeline",
                    "performed_via_github_app": None,
                    "state_reason": None,
                    "score": 1.0,
                },
                {
                    "url": "https://api.github.com/repos/con/nwb2bids/issues/253",
                    "repository_url": "https://api.github.com/repos/con/nwb2bids",
                    "labels_url": "https://api.github.com/repos/con/nwb2bids/issues/253/labels{/name}",
                    "comments_url": "https://api.github.com/repos/con/nwb2bids/issues/253/comments",
                    "events_url": "https://api.github.com/repos/con/nwb2bids/issues/253/events",
                    "html_url": "https://github.com/con/nwb2bids/pull/253",
                    "id": 3782925016,
                    "node_id": "PR_kwDOLaBElc67m3AO",
                    "number": 253,
                    "title": "Standardized all reference to notifications",
                    "user": {
                        "login": "CodyCBakerPhD",
                        "id": 51133164,
                        "node_id": "MDQ6VXNlcjUxMTMzMTY0",
                        "avatar_url": "https://avatars.githubusercontent.com/u/51133164?v=4",
                        "gravatar_id": "",
                        "url": "https://api.github.com/users/CodyCBakerPhD",
                        "html_url": "https://github.com/CodyCBakerPhD",
                        "followers_url": "https://api.github.com/users/CodyCBakerPhD/followers",
                        "following_url": "https://api.github.com/users/CodyCBakerPhD/following{/other_user}",
                        "gists_url": "https://api.github.com/users/CodyCBakerPhD/gists{/gist_id}",
                        "starred_url": "https://api.github.com/users/CodyCBakerPhD/starred{/owner}{/repo}",
                        "subscriptions_url": "https://api.github.com/users/CodyCBakerPhD/subscriptions",
                        "organizations_url": "https://api.github.com/users/CodyCBakerPhD/orgs",
                        "repos_url": "https://api.github.com/users/CodyCBakerPhD/repos",
                        "events_url": "https://api.github.com/users/CodyCBakerPhD/events{/privacy}",
                        "received_events_url": "https://api.github.com/users/CodyCBakerPhD/received_events",
                        "type": "User",
                        "user_view_type": "public",
                        "site_admin": False,
                    },
                    "labels": [
                        {
                            "id": 9462364765,
                            "node_id": "LA_kwDOLaBElc8AAAACNAA6XQ",
                            "url": "https://api.github.com/repos/con/nwb2bids/labels/minor",
                            "name": "minor",
                            "color": "f1a60e",
                            "default": False,
                            "description": "Increment the minor version when merged",
                        },
                        {
                            "id": 9462365107,
                            "node_id": "LA_kwDOLaBElc8AAAACNAA7sw",
                            "url": "https://api.github.com/repos/con/nwb2bids/labels/internal",
                            "name": "internal",
                            "color": "696969",
                            "default": False,
                            "description": "Changes only affect the internal API",
                        },
                        {
                            "id": 9462365474,
                            "node_id": "LA_kwDOLaBElc8AAAACNAA9Ig",
                            "url": "https://api.github.com/repos/con/nwb2bids/labels/released",
                            "name": "released",
                            "color": "11a990",
                            "default": False,
                            "description": "This issue/pull request has been released.",
                        },
                    ],
                    "state": "closed",
                    "locked": False,
                    "assignees": [
                        {
                            "login": "CodyCBakerPhD",
                            "id": 51133164,
                            "node_id": "MDQ6VXNlcjUxMTMzMTY0",
                            "avatar_url": "https://avatars.githubusercontent.com/u/51133164?v=4",
                            "gravatar_id": "",
                            "url": "https://api.github.com/users/CodyCBakerPhD",
                            "html_url": "https://github.com/CodyCBakerPhD",
                            "followers_url": "https://api.github.com/users/CodyCBakerPhD/followers",
                            "following_url": "https://api.github.com/users/CodyCBakerPhD/following{/other_user}",
                            "gists_url": "https://api.github.com/users/CodyCBakerPhD/gists{/gist_id}",
                            "starred_url": "https://api.github.com/users/CodyCBakerPhD/starred{/owner}{/repo}",
                            "subscriptions_url": "https://api.github.com/users/CodyCBakerPhD/subscriptions",
                            "organizations_url": "https://api.github.com/users/CodyCBakerPhD/orgs",
                            "repos_url": "https://api.github.com/users/CodyCBakerPhD/repos",
                            "events_url": "https://api.github.com/users/CodyCBakerPhD/events{/privacy}",
                            "received_events_url": "https://api.github.com/users/CodyCBakerPhD/received_events",
                            "type": "User",
                            "user_view_type": "public",
                            "site_admin": False,
                        }
                    ],
                    "milestone": None,
                    "comments": 3,
                    "created_at": "2026-01-05T21:32:45Z",
                    "updated_at": "2026-01-07T19:31:16Z",
                    "closed_at": "2026-01-06T17:12:45Z",
                    "assignee": {
                        "login": "CodyCBakerPhD",
                        "id": 51133164,
                        "node_id": "MDQ6VXNlcjUxMTMzMTY0",
                        "avatar_url": "https://avatars.githubusercontent.com/u/51133164?v=4",
                        "gravatar_id": "",
                        "url": "https://api.github.com/users/CodyCBakerPhD",
                        "html_url": "https://github.com/CodyCBakerPhD",
                        "followers_url": "https://api.github.com/users/CodyCBakerPhD/followers",
                        "following_url": "https://api.github.com/users/CodyCBakerPhD/following{/other_user}",
                        "gists_url": "https://api.github.com/users/CodyCBakerPhD/gists{/gist_id}",
                        "starred_url": "https://api.github.com/users/CodyCBakerPhD/starred{/owner}{/repo}",
                        "subscriptions_url": "https://api.github.com/users/CodyCBakerPhD/subscriptions",
                        "organizations_url": "https://api.github.com/users/CodyCBakerPhD/orgs",
                        "repos_url": "https://api.github.com/users/CodyCBakerPhD/repos",
                        "events_url": "https://api.github.com/users/CodyCBakerPhD/events{/privacy}",
                        "received_events_url": "https://api.github.com/users/CodyCBakerPhD/received_events",
                        "type": "User",
                        "user_view_type": "public",
                        "site_admin": False,
                    },
                    "author_association": "COLLABORATOR",
                    "type": None,
                    "active_lock_reason": None,
                    "draft": False,
                    "pull_request": {
                        "url": "https://api.github.com/repos/con/nwb2bids/pulls/253",
                        "html_url": "https://github.com/con/nwb2bids/pull/253",
                        "diff_url": "https://github.com/con/nwb2bids/pull/253.diff",
                        "patch_url": "https://github.com/con/nwb2bids/pull/253.patch",
                        "merged_at": "2026-01-06T17:12:45Z",
                    },
                    "body": (
                        "Convention swapped to referring to these as notifications a while back, and that went into "
                        "effect piecewise for new features with occasional fixes in older classes whenever they were "
                        "obvious\r\n\r\nThis finally goes through everything and standardizes references to the old "
                        "'messages' into 'notifications'\r\n\r\nIt also starts to establish an official "
                        "`notifications` public submodule, though this is empty ATM\r\n\r\nNext steps:\r\n- "
                        "Rename `InspectionResults` similarly\r\n- Rename all 'Inspection' references similarly since "
                        "they do more than just inspect sometimes\r\n- Standardize the expected output assertions "
                        "throughout test suite\r\n- Create a common registry of notifications so they can only be "
                        "defined once and used everywhere (with certain inputs)\r\n- Rethink notification categories"
                    ),
                    "reactions": {
                        "url": "https://api.github.com/repos/con/nwb2bids/issues/253/reactions",
                        "total_count": 0,
                        "+1": 0,
                        "-1": 0,
                        "laugh": 0,
                        "hooray": 0,
                        "confused": 0,
                        "heart": 0,
                        "rocket": 0,
                        "eyes": 0,
                    },
                    "timeline_url": "https://api.github.com/repos/con/nwb2bids/issues/253/timeline",
                    "performed_via_github_app": None,
                    "state_reason": None,
                    "score": 1.0,
                },
                {
                    "url": "https://api.github.com/repos/con/nwb2bids/issues/251",
                    "repository_url": "https://api.github.com/repos/con/nwb2bids",
                    "labels_url": "https://api.github.com/repos/con/nwb2bids/issues/251/labels{/name}",
                    "comments_url": "https://api.github.com/repos/con/nwb2bids/issues/251/comments",
                    "events_url": "https://api.github.com/repos/con/nwb2bids/issues/251/events",
                    "html_url": "https://github.com/con/nwb2bids/pull/251",
                    "id": 3782292109,
                    "node_id": "PR_kwDOLaBElc67kwfE",
                    "number": 251,
                    "title": "Move data generation page out of main tutorials",
                    "user": {
                        "login": "CodyCBakerPhD",
                        "id": 51133164,
                        "node_id": "MDQ6VXNlcjUxMTMzMTY0",
                        "avatar_url": "https://avatars.githubusercontent.com/u/51133164?v=4",
                        "gravatar_id": "",
                        "url": "https://api.github.com/users/CodyCBakerPhD",
                        "html_url": "https://github.com/CodyCBakerPhD",
                        "followers_url": "https://api.github.com/users/CodyCBakerPhD/followers",
                        "following_url": "https://api.github.com/users/CodyCBakerPhD/following{/other_user}",
                        "gists_url": "https://api.github.com/users/CodyCBakerPhD/gists{/gist_id}",
                        "starred_url": "https://api.github.com/users/CodyCBakerPhD/starred{/owner}{/repo}",
                        "subscriptions_url": "https://api.github.com/users/CodyCBakerPhD/subscriptions",
                        "organizations_url": "https://api.github.com/users/CodyCBakerPhD/orgs",
                        "repos_url": "https://api.github.com/users/CodyCBakerPhD/repos",
                        "events_url": "https://api.github.com/users/CodyCBakerPhD/events{/privacy}",
                        "received_events_url": "https://api.github.com/users/CodyCBakerPhD/received_events",
                        "type": "User",
                        "user_view_type": "public",
                        "site_admin": False,
                    },
                    "labels": [
                        {
                            "id": 6631660901,
                            "node_id": "LA_kwDOLaBElc8AAAABi0cdZQ",
                            "url": "https://api.github.com/repos/con/nwb2bids/labels/documentation",
                            "name": "documentation",
                            "color": "cfd3d7",
                            "default": True,
                            "description": "Changes only affect the documentation",
                        },
                        {
                            "id": 9462365474,
                            "node_id": "LA_kwDOLaBElc8AAAACNAA9Ig",
                            "url": "https://api.github.com/repos/con/nwb2bids/labels/released",
                            "name": "released",
                            "color": "11a990",
                            "default": False,
                            "description": "This issue/pull request has been released.",
                        },
                    ],
                    "state": "closed",
                    "locked": False,
                    "assignees": [
                        {
                            "login": "CodyCBakerPhD",
                            "id": 51133164,
                            "node_id": "MDQ6VXNlcjUxMTMzMTY0",
                            "avatar_url": "https://avatars.githubusercontent.com/u/51133164?v=4",
                            "gravatar_id": "",
                            "url": "https://api.github.com/users/CodyCBakerPhD",
                            "html_url": "https://github.com/CodyCBakerPhD",
                            "followers_url": "https://api.github.com/users/CodyCBakerPhD/followers",
                            "following_url": "https://api.github.com/users/CodyCBakerPhD/following{/other_user}",
                            "gists_url": "https://api.github.com/users/CodyCBakerPhD/gists{/gist_id}",
                            "starred_url": "https://api.github.com/users/CodyCBakerPhD/starred{/owner}{/repo}",
                            "subscriptions_url": "https://api.github.com/users/CodyCBakerPhD/subscriptions",
                            "organizations_url": "https://api.github.com/users/CodyCBakerPhD/orgs",
                            "repos_url": "https://api.github.com/users/CodyCBakerPhD/repos",
                            "events_url": "https://api.github.com/users/CodyCBakerPhD/events{/privacy}",
                            "received_events_url": "https://api.github.com/users/CodyCBakerPhD/received_events",
                            "type": "User",
                            "user_view_type": "public",
                            "site_admin": False,
                        }
                    ],
                    "milestone": None,
                    "comments": 5,
                    "created_at": "2026-01-05T17:29:40Z",
                    "updated_at": "2026-01-07T19:31:25Z",
                    "closed_at": "2026-01-05T18:49:18Z",
                    "assignee": {
                        "login": "CodyCBakerPhD",
                        "id": 51133164,
                        "node_id": "MDQ6VXNlcjUxMTMzMTY0",
                        "avatar_url": "https://avatars.githubusercontent.com/u/51133164?v=4",
                        "gravatar_id": "",
                        "url": "https://api.github.com/users/CodyCBakerPhD",
                        "html_url": "https://github.com/CodyCBakerPhD",
                        "followers_url": "https://api.github.com/users/CodyCBakerPhD/followers",
                        "following_url": "https://api.github.com/users/CodyCBakerPhD/following{/other_user}",
                        "gists_url": "https://api.github.com/users/CodyCBakerPhD/gists{/gist_id}",
                        "starred_url": "https://api.github.com/users/CodyCBakerPhD/starred{/owner}{/repo}",
                        "subscriptions_url": "https://api.github.com/users/CodyCBakerPhD/subscriptions",
                        "organizations_url": "https://api.github.com/users/CodyCBakerPhD/orgs",
                        "repos_url": "https://api.github.com/users/CodyCBakerPhD/repos",
                        "events_url": "https://api.github.com/users/CodyCBakerPhD/events{/privacy}",
                        "received_events_url": "https://api.github.com/users/CodyCBakerPhD/received_events",
                        "type": "User",
                        "user_view_type": "public",
                        "site_admin": False,
                    },
                    "author_association": "COLLABORATOR",
                    "type": None,
                    "active_lock_reason": None,
                    "draft": False,
                    "pull_request": {
                        "url": "https://api.github.com/repos/con/nwb2bids/pulls/251",
                        "html_url": "https://github.com/con/nwb2bids/pull/251",
                        "diff_url": "https://github.com/con/nwb2bids/pull/251.diff",
                        "patch_url": "https://github.com/con/nwb2bids/pull/251.patch",
                        "merged_at": "2026-01-05T18:49:18Z",
                    },
                    "body": (
                        "Yarik had requested that the data generation sections not be a part of the main tutorials "
                        "page\r\n\r\nThey should now show up on the left navbar of the tutorials page (and are "
                        "linked in third paragraph of tutorial intro)"
                    ),
                    "reactions": {
                        "url": "https://api.github.com/repos/con/nwb2bids/issues/251/reactions",
                        "total_count": 0,
                        "+1": 0,
                        "-1": 0,
                        "laugh": 0,
                        "hooray": 0,
                        "confused": 0,
                        "heart": 0,
                        "rocket": 0,
                        "eyes": 0,
                    },
                    "timeline_url": "https://api.github.com/repos/con/nwb2bids/issues/251/timeline",
                    "performed_via_github_app": None,
                    "state_reason": None,
                    "score": 1.0,
                },
            ],
        },
    }
    assert test_info == expected_info
